### ISSUE TITLE
Installation questions

### ISSUE THREAD

**Issue by pkdavidson** [Esri/arcgis-cookbook#16]
Gentlemen:
Great to find this cookbook.  
Being new to Chef but having had it on my radar for sometime, this is truly awesome.
And thank you for all the work you've put into this delicious soup.

I have been having one stopper issue and a number of questions:

1. Major issue: install fails at trying to Start ArcGIS Server.
   The issue here is easily fixed, I think, but it might helpful to have this documented.
   The ArcGIS runasuser account needs to be admin level and needs to already exist and you need to be logged in as this account, correct?    I was just giving this the name of new account so when created it it was not given admin level perms.  Which meant it could not access the C:\arcgisserver folders, etc...
My next step is to restore a snapshot of the VM, build a new local admin user, log in as that user and let it rip.  fingers crossed.

2. I would prefer to use a domain level account because that's how we install all of our Arc Servers, etc...
However, I haven't been able to figure out how to set that in the run as line:
   "arcgis" : {
 	 "run_as_password" : "somePW0rd",
	 "run_as_user" : "domainName\\userName"
   },
doesn't work.... 
I suspect it's related to the action:create which will fail since I am not a domain admin hence I cannot create a domain account.  But it also just looks like the recipe is not setup for domain account usage.
Anyway to pull that one off?  And, yes, I've been rolling through the Chef.io docs but no luck so far.  Too much a newbie I think to really have a clue even.

3. When installing chef-client: do we want the powershell client and the service client?
Powershell seems harmless so I put it in there.  Service client....  I have an aversion to services.  
But I installed it since better to have it and not use it than need it and have the install crash again.

4. At the end of system.rb recipe, there's talk about the Windows firewall port settings.
These of course are clearly documented in the Esri install help files so it's nothing new.
But since the Chef is configuring IIS, etc... I would have assumed it would be opening up ports.
But after finding those comments, I assume we have to manually open the ports, or at least I did.
Is it not possible to do that via Chef?
Would be nice to see this documented.  Not sure everyone will be digging around and not just running the Chef install based on your getting started guide.  I know we like to keep those guides short, but maybe a more complete version for the OCD among us?    No ports open, things won't work and now the poor installer is digging around to find the error as to why Portal is not doing its thing, instead of just praising the beauty of Chef.    :-)

5. Any chance you have worked out a Vagrant file for Windows Server 2012 R2 that uses these Recipes

6. What's the purpose of the webgis-windows.json vs. node-windows.json  Same run list, webgis is missing the iis definition and webgis is missing some info (so it's default to things like FQDN for domain name, right?  is the webgis just a cut down version, or not setup to be https?  Confusing for the newbie... But the docs clearly call out node-windows.json

7. Regarding installation of desktop:  I skipped it for now because we're on concurrent seating with license managers  and unfortunately, the link for silent install you provided is down (503).  So is your blog post for that matter.  An Esri server maintenance period?  (both are now backup again...)

I can probably piece together how to do it from other Issue posts.  But it would be nice to see a block all laid out.  Now that the silent install is back up, I believe this is the layout of a Concurrent, ArcInfo license with two license managers (for failover):
{
   "desktop" : {
	 "setup" : "\\\\OurInstallServer\\ArcGIS10.3.1\\Desktop\\Setup.exe",
	 "esri_license_host" : "mylicSrvr1;mylicSrvr2",
	 "software_class" : "Professional",
	 "seat_preference" : "Float",
	 "desktop_config" : "True",
	"install_features" : "ArcMap,Python,ArcCatalog"
   },
   "run_list":[
      "recipe[arcgis::desktop]",
   ]
}

Also, in providers/desktop.rb, RENEWAL_CHECK is still in there.  
And desktop_config still missing from desktop.rb as per your instructions in: https://github.com/Esri/arcgis-cookbook/issues/13  
EDIT: looks like master branch has those gone....  
Looks like I need to pull a new version

many thanks for your help and this tool.

**Comment by pbobov** [comment]
Hi Paul,

Thanks for trying out the cookbook!

1. The arcgis user account does not have to have (and ideally should not have) administrative privileges, however the account chef-client is running under must be an administrator. chef-client tries to create the arcgis account and to grant that account permissions to all the directories used by arcgis software, etc.

2. So far the cookbook does not support domain accounts. The problem will be fixed in the next 1.1.2 release of the cookbook in a few days. The cookbook actually tries to create/update the user account with given username and password and it fails for domain accounts. The temporary workaround is to remove  
```
  user node['arcgis']['run_as_user'] do
    comment 'ArcGIS user account'
    supports :manage_home => true
    password node['arcgis']['run_as_password']
    action :create
  end
```
from the system recipe if you use an existing domain account. Other parts of the cookbook should support domain accounts.

3. Powershell client and the service client are not required by the cookbook.

4. So far the windows firewall configuration is not supported. It's on our TODO list. I'm sorry for the confusing comments. 

5. We are thinking about using Test Kitchen for testing the cookbook. This will require Vagrant files, but there is no ETA on this yet.

6. Yes. Essentially, webgis-windows.json is a cut down version of node-windows.json. Web GIS is a deployment pattern of ArcGIS that includes ArcGIS Portal, Server, and DataStore. Eventually, we will have a whole zoo of node.json templates for different deployment patterns.

7. I'll try to figure out what is going on...

Regards,
Pavel

**Comment by pkdavidson** [comment]
Thanks for the quick replies!
Look forward to the complete kitchen you're working on.

**Comment by powersparks** [comment]
Does the recipe support domain users now?

**Comment by pbobov** [comment]
Yes. Domain users are now supported by ArcGIS Chef cookbooks.

**Comment by powersparks** [comment]
I just saw your reply. thanks.. I opened a new issue while I track the implementation problem.
