### ISSUE TITLE
Portal "create site" creates the portal content folder in wrong place

### ISSUE THREAD

**Issue by sodtom** [Esri/arcgis-cookbook#178]
Seems that portal's "create site" functionality in ArcGIS Enterprise cookbook is creating the content folder in wrong place when/if shared network drive is used for "content_dir". Shared folder is needed for HA configuration where content should be shared. We're using DFS namespaces for share definitions in the domain.

We have Chef node configuration (.json) with following content definition for portal:
"content_dir":"\\\\test.domain.com\\Shared\\Data\\ArcGIS\\portal"

Installation creates the specified "portal" folder just fine. However when recipe executes the "create_site" it creates a separate "content" folder to the parent "ArcGIS" folder (at the same level with "portal" folder) - NOT in the portal folder as specified with the "content_dir" definition.

So, we end up with a folder structure like 

![image](https://user-images.githubusercontent.com/44703543/47921027-46edaf00-debc-11e8-913b-3350b138f5ee.png)

which is wrong and portal ends to mess!

This content folder should to my understanding be created inside the portal folder, NOT at the same level.

Chef client version 13.8.5
ArcGIS Cookbook: 3.2.0 and 3.2.1

**Comment by sodtom** [comment]
Seems that the recipe logic is not perfect, but I managed to fix this issue by defining the content_dir as

"content_dir":"\\test.domain.com\Shared\Data\ArcGIS\portal\content"

which eliminates the recipe to create this content elsewhere.

**Comment by cameronkroeker** [comment]
> Seems that the recipe logic is not perfect, but I managed to fix this issue by defining the content_dir as
> 
> "content_dir":"\test.domain.com\Shared\Data\ArcGIS\portal\content"
> 
> which eliminates the recipe to create this content elsewhere.

I believe this issue is related to the Portal Create Site API, rather than the cookbook. The portal setup doesn't require appending 'content' to the end of the path because the setup will create this directory. Therefore, `node['arcgis']['portal']['data_dir']` can be set to C:\arcgisportal and it will create C:\arcgisportal\content.

However, the Create Site behaves a bit differently and needs the 'content' directory specified in the path. This is because it uses the "connectionString":

`contentStore={"type": "fileStore","provider": "FileSystem","connectionString": "C:/arcgisportal/content"}`

https://developers.arcgis.com/rest/enterprise-administration/portal/create-site.htm

We have updated the attribute list to hopefully make this more clear.

`node['arcgis']['portal']['content_store_connection_string'] = Portal for ArcGIS content store connection string. Default connection string is node['arcgis']['portal']['content_dir'].`

node['arcgis']['portal']['content_dir'] = Portal for ArcGIS content directory. Default directory is C:\arcgisportal\content on Windows and /arcgis/portal/usr/arcgisportal/content on Linux.

`node['arcgis']['portal']['data_dir'] = Data directory path used by Portal for ArcGIS setup. The path must be a local directory, not a shared network directory. Dafault path on Windows is C:\arcgisportal, on Linux is /arcgis/portal/usr/arcgisportal/.`

https://github.com/Esri/arcgis-cookbook/tree/master/cookbooks/arcgis-enterprise#portal
