### ISSUE TITLE
10.7 support

### ISSUE THREAD

**Issue by jsthusker** [Esri/arcgis-cookbook#188]
10.7 Enterprise has some important functionality that is not currently available. I am on the early adopter program and was wondering a time frame for Chef cookbook compatibility.  And or/if there would be a work around for making the existing arcgis-cookbook work.

**Comment by SBYGIS** [comment]
@jsthusker 

The issue is the hardcoded "Product Code" in the form of a GUID in the ruby files.  ie. 

arcgis-desktop/attributes/desktop.rb
```ruby
case node['arcgis']['version']
    when '10.6.1'
      desktop['product_code'] = '{FA2E2CBC-0697-4C71-913E-8C65B5A611E8}'
    when '10.6'
      desktop['product_code'] = '{F8206086-367E-44E4-9E24-92E9E057A63D}'
    when '10.5.1'
      desktop['product_code'] = '{4740FC57-60FE-45BB-B513-3309F6B73183}'
    when '10.5'
      desktop['product_code'] = '{76B58799-3448-4DE4-BA71-0FDFAA2A2E9A}'
    when '10.4.1'
      desktop['product_code'] = '{CB0C9578-75CB-45E5-BD81-A600BA33B0C3}'
    when '10.4'
      desktop['product_code'] = '{72E7DF0D-FFEE-43CE-A5FA-43DFC25DC087}'
    else
      Chef::Log.warn 'Unsupported ArcGIS version'
    end
```

Essentially if there is no valid version provided in the [arcgis][version] variable the desktop[product_code] is not assigned and error's out as an Unsupported Version.  This should be fairly simple to implement from the development standpoint but without knowing how they create this GUID there is not really a good way to workaround unless you try to pass an old version and set the setup file variable as the target version you want to install (and pray it works).
