### ISSUE TITLE
SystemCallError: The specified service does not exist as an installed service.

### ISSUE THREAD

**Issue by mkarikari** [Esri/arcgis-cookbook#191]
Im kind of stuck, Im testing out new 3.2.1 cookbooks and currently trying to install a single arcgis server, but any time i run the following role

```
{
  "name": "arcgis-server_1061",
  "description": "Standard ArcGIS Server with Advance License",
  "default_attributes": {
    "arcgis":{
    "version":"10.6.1",
	"cache_authorization_files": false,
    "repository":{
      "archives":"\\\\XXXX\\Installs",
	  "setups":"E:\\Installs"
	  },
      "server":{
      "admin_username":"XXXX",
      "admin_password":"XXXXX",
		"directories_root":"E:\\share\\arcgisserver",
		"install_dir":"E:\\Programs\\ArcGIS\\Server",
		"authorization_file":"E:\\Installs\\ArcGISGISServerAdvanced_ArcGISServer.prvc"

  }
  }
  },
  "run_list":[
    "recipe[arcgis-enterprise::system]",
    "recipe[arcgis-enterprise::server]"
  ]
} 
```

I get the following error seen in attachment. Is there something I'm missing?

[chef-stacktrace.txt](https://github.com/Esri/arcgis-cookbook/files/2756854/chef-stacktrace.txt)

**Comment by pbobov** [comment]
This kind of problem can happen if "ArcGIS Server 10.6.1" application is installed (Chef found the app product code {F62B418D-E9E4-41CE-9E02-167BE4276105} in the windows registry), but "ArcGIS Server" windows service is not there. In that case Chef does not run server's Setup.exe because it assumes that server is already installed, yet it tries to configure "ArcGIS Server" and fails there.

It's hard to say why that happened. I guess ArcGIS Server was not uninstalled correctly.

**Comment by mkarikari** [comment]
Interesting, I used the defualt uninstall feature from the Windows > System Setting.  Is there any pointers you can give where I can check and remove said registry reference?

**Comment by mkarikari** [comment]
Was able to resolve, I realized that ArcGIS Desktop 10.5.1 was still install and was causing the conflict and subsequent erro
