### ISSUE TITLE
Not recognizing “setups_archive” variable 

### ISSUE THREAD

**Issue by MantalopePG** [Esri/arcgis-cookbook#235]
In the arcgis-enterprise-windows.json file I have changed the following variable: 
"setup":"C:\\ArcGIS\\10.7\\Portal\\Setup.exe"
to 
"setups_archive":"\\\\share\\install\\ArcGIS\\Enterprise\\10.7.1\\Portal_for_ArcGIS_Windows_1071_169688.exe",

However I am getting the error:
STDERR: The system cannot find the path specified.
---- End output of "C:\Users\arcsrvradmin\Documents\ArcGIS 10.7.1\PortalForArcGIS\Setup.exe"

**Comment by cameronkroeker** [comment]
@MantalopePG 

Let's try the following:

`"setups_archive":"\\\\share\\install\\ArcGIS\\Enterprise\\10.7.1\\Portal_for_ArcGIS_Windows_1071_169688.exe",`

**Comment by MantalopePG** [comment]
Would that be for all the set up variables or just portal? 
I'm going off the documentation here:
https://github.com/Esri/arcgis-cookbook/wiki/Deploy-a-base-ArcGIS-Enterprise-deployment-on-a-single-machine

**Comment by cameronkroeker** [comment]
> Would that be for all the set up variables or just portal?
> I'm going off the documentation here:
> https://github.com/Esri/arcgis-cookbook/wiki/Deploy-a-base-ArcGIS-Enterprise-deployment-on-a-single-machine

For all the setup variables. I went ahead and updated the wiki/Deploy-a-base-ArcGIS-Enterprise-deployment-on-a-single-machine doc to reflect "setup" and "setup_archive" instead of "setups" and "setups_archive".

Also, all variables can be found [here.](https://github.com/Esri/arcgis-cookbook/tree/master/cookbooks/arcgis-enterprise#server)

Thanks!
