### ISSUE TITLE
chef hostsfile

### ISSUE THREAD

**Issue by drobinson13** [Esri/arcgis-cookbook#237]
Hi,

In the context of an arcgis enterprise upgrade on windows - does chef utilise the hostsfile deployed on the system - C:\Windows\System32\Drivers\etc\hosts

Or does it require its own hostsfile be populated?

I am keen to QA our upgrades by using the hostsfile (retaining the production DNS).

**Comment by Nickolaitc** [comment]
Hey @drobinson13 

Chef can make a host update if designated within the roles file.

We will need to access the roles file being utilized and in the "arcgis" segment, we will need to include "hosts" , bracket, hostname inclusion, and an empty quote (empty quotes = local IP).  Please check the example below:

 "arcgis":{
    "run_as_user":"usernamethings",
    "run_as_password":"passwordthings",
    "version":"10.7.1",
	"hosts":{
		"trevor.test.com": ""
	  }

We will want to make sure that within the run_list we have "recipe[arcgis-enterprise::system]" in there as the system cookbook is what kicks off the /etc/hosts file manipulation.

**Comment by pbobov** [comment]
Changes to C:\Windows\System32\Drivers\etc\hosts make the system-wide effect. They definitely can have affect  ArcGIS Enterprise upgrades with Chef.

For ArcGIS Enterprise deployment in certain cases we use hosts file to alias certain host and domain names, for example:
1. Use fixed alias like FILESERVER instead of actual file server machine hostname or IP address, so the file server machine can be easily replaced/recovered without other configuration changes.
2. Loop back the load balancer's domain name to the local IP address to shorten the loop and to prevent chicken-egg sort of problems with the load balancer's health checks.

**Comment by cameronkroeker** [comment]
Closing since original question was addressed.
