### ISSUE TITLE
Deploying a Geoevent server question

### ISSUE THREAD

**Issue by Mike-DM** [Esri/arcgis-cookbook#291]
Hi all,

I'm brand new to Chef and I have been reading this site and the watching some tutorial videos.  I'm in the process of deploying  ArcGIS Enterprise 10.9 using chef and cookbooks 3.7.0.   I made a Windows 2016 Chef workstation (version 21.6.497) and an Ubuntu Chef Server.   All my clients/nodes are Windows 2016.  I've been following the guide here.

https://github.com/Esri/arcgis-cookbook/wiki/Automate-a-multi-machine-ArcGIS-Enterprise-deployment-on-Windows-using-Chef-Server

It has gone fairly smoothly, I have Base Enterprise deployed along with a Big Datastore and Geoanalytics server.  Now I'm trying to make a Geoevent sever and I notice there isn't a file for Geoevent under "roles".  I have the cookbook and templates, but following the guide I mentioned above, each server has had a corresponding "role" JSON file.  

Can anyone assist me with how I would deploy a Geoevent server?  Do I need to use the template with Chef Zero commands  directly on the workstation that will become GeoEvent or will I need to use a template to create a "role" file so I can deploy Geoevent with Chef Workstation?

I also want to mention that when I first tried to deploy Base Enterprise using 3.7.0 cookbooks, I received missing dependency cookbook errors.   I had to go into the 3.6.1 cookbooks and get the cookbooks for s3_files, windows, windows_firewall, hostsfile, openssl, nfs,.... etc,.

**Comment by cameronkroeker** [comment]
Hello @Mike-DM,

You can use the following json files for GeoEvent Server:

https://github.com/Esri/arcgis-cookbook/tree/master/templates/arcgis-geoevent-server/10.9/windows

If using Chef Server, move them to the roles directory.

For the missing dependency issue, did you download and use `arcgis-3.7.0-cookbooks.zip`
the from the following location?

https://github.com/Esri/arcgis-cookbook/releases/tag/v3.7.0

This will contain all necessary cookbooks. Otherwise if downloading the cookbook from https://github.com/Esri/arcgis-cookbook/tree/v3.7.0 it will only contain the Esri Cookbooks and not the third party dependency cookbooks.

Happy Automating,
Cameron K.

**Comment by Mike-DM** [comment]
Hi Cameron,

Thanks a lot for your assistance!  I will modify the templates as you suggested and put them in my roles directory for upload to my Chef Server.

You're right, I got the cookbooks from https://github.com/Esri/arcgis-cookbook/tree/v3.7.0 so that explain why I was missing the third party dependency cookbooks.  Thanks for pointing me to the other location for the full cookbooks.

Best Regards,
Mike

**Comment by cameronkroeker** [comment]
You're welcome! Since the original question has been addressed I'll go ahead and close this issue. However, feel free to open a new issue if there are further questions/issues that may arise.

Thanks,
Cameron
