### ISSUE TITLE
default directory for Chef Workstation on Windows

### ISSUE THREAD

**Issue by awittner** [Esri/arcgis-cookbook#297]
Step 3 - for multimachine on windows - lists an older default directory location. according to current chef workstation doc:
" installer uses the C:\opscode\chef-workstation\ directory. "
see: https://docs.chef.io/workstation/install_workstation/ 

C:\chef-repo is no longer default.

**Comment by cameronkroeker** [comment]
Hi @awittner,

The `C:\opscode\chef-workstation\` directory is where the installer\executable files resides for Chef Workstation (chef-client, chef-apply, etc), whereas the `C:\chef-repo` is a separate directory that can be created to place the cookbooks, roles, environment files etc. You don't have to use `C:\chef-repo` as you can really place the cookbooks anywhere. The reason the [doc](https://github.com/Esri/arcgis-cookbook/wiki/Automate-a-multi-machine-ArcGIS-Enterprise-deployment-on-Windows-using-Chef-Server#chef-workstation) suggests `C:\chef-repo` is because I believe this is the default location the starter kit (chef-starter.zip) from the free hosted Chef Server gets extracted to.

Thanks,
Cameron K.
