### ISSUE TITLE
Patches recipe in cookbooks version 4.0

### ISSUE THREAD

**Issue by Ayushyadav19** [Esri/arcgis-cookbook#325]
Hi @cameronkroeker ,

The latest version (4.0) of arcgis-enterprise cookbook didn't contain the patches recipe although it has install_patches recipe. But it will be easy and convenient to provide a patches folder instead of providing individual patches for each ArcGIS enterprise components.

The cookbook (arcgis-enterprise) version (3.8) contains both the recipes i,e. install_patches + patches. 

Kindly have a look into it and I request you add and update the cookbook if possible.

Thanks
Ayush

**Comment by cameronkroeker** [comment]
Hi @Ayushyadav19,

The patches recipe in Chef Cookbooks for ArcGIS v4.0.0 is now in arcgis-repository cookbook `recipe[arcgis-repository::patches]` because it downloads patches for specific products to a central location. Then `recipe[arcgis-enterprise::install_patches]` is used to install the patches.

Here are some examples for 10.9.1.

#### Windows


**Download Patches:**
https://github.com/Esri/arcgis-cookbook/blob/237b0e39fca0a3b5988b997430bf7beb3637e039/templates/arcgis-enterprise-base/10.9.1/windows/arcgis-enterprise-patches.json#L1-L19

**Install Patches:**
https://github.com/Esri/arcgis-cookbook/blob/237b0e39fca0a3b5988b997430bf7beb3637e039/templates/arcgis-enterprise-base/10.9.1/windows/arcgis-enterprise-patches-apply.json#L1-L35

#### Linux

**Download Patches:**
https://github.com/Esri/arcgis-cookbook/blob/237b0e39fca0a3b5988b997430bf7beb3637e039/templates/arcgis-enterprise-base/10.9.1/linux/arcgis-enterprise-patches.json#L1-L19

**Install Patches:**
https://github.com/Esri/arcgis-cookbook/blob/237b0e39fca0a3b5988b997430bf7beb3637e039/templates/arcgis-enterprise-base/10.9.1/linux/arcgis-enterprise-patches-apply.json#L1-L38

For more details and instructions check out the following resources:

https://esri.github.io/arcgis-cookbook/tutorials/arcgis-enterprise-base-patches/4.0.0.html

https://esri.github.io/arcgis-cookbook/templates/arcgis-enterprise-base/10.9.1.html#install-base-arcgis-enterprise-patches-and-updates

https://esri.github.io/arcgis-cookbook/cookbooks/arcgis-repository/4.0.0.html#patches

https://esri.github.io/arcgis-cookbook/cookbooks/arcgis-enterprise/4.0.0.html#install_patches

Thanks,
Cameron K.

**Comment by Ayushyadav19** [comment]
Thanks, @cameronkroeker

**Comment by cameronkroeker** [comment]
> Thanks, @cameronkroeker

I would like to also note that the reason for listing out the patch file names is sometimes necessary is because in some cases the patch install order matters. For example, ArcGIS Server 10.9.1 (Windows) requires the[ Setup Program patch](https://support.esri.com/en/Products/Enterprise/arcgis-server/ArcGIS-Server/10-9-1#downloads?id=7956), to be installed first. However, in use cases where the patch install order doesn't matter you can use a wild card method instead. 

Below is an example, it will install all patches (random order) in `/opt/software/archives/patches` directory that contain the file names `ArcGIS-1091-S-*.tar`, `ArcGIS-1091-PFA-*.tar`, and `ArcGIS-1091-DS-*.tar`.

Here is an example:

```json
 { 
     "arcgis": { 
         "version": "10.9.1", 
         "run_as_user": "arcgis", 
         "repository": { 
             "patches": "/opt/software/archives/patches" 
         }, 
         "portal": { 
             "install_dir": "/opt", 
             "patches": [ 
                 "ArcGIS-1091-PFA-*.tar" 
             ] 
         }, 
         "server": { 
             "install_dir": "/opt", 
             "patches": [ 
                 "ArcGIS-1091-S-*.tar"
             ] 
         }, 
         "data_store": { 
             "install_dir": "/opt", 
             "patches": [ 
                 "ArcGIS-1091-DS-*.tar" 
             ] 
         }, 
         "web_adaptor": { 
             "patches": [] 
         } 
     }, 
     "run_list": [ 
         "recipe[arcgis-enterprise::install_patches]" 
     ] 
 }
```

Thanks,
Cameron K.

**Comment by Ayushyadav19** [comment]
This is great! Thanks @cameronkroeker
