### ISSUE TITLE
Can't find Portal product when installing Excalibur

### ISSUE THREAD

**Issue by tatornator12** [Esri/arcgis-cookbook#343]
Hey @cameronkroeker,

When trying to install Excalibur on an Enterprise version 11.0 Linux install using Chef on a single EC2 instance, the Excalibur outputs the below message:

<img width="400" alt="Screen Shot 2023-04-20 at 1 21 56 PM" src="https://user-images.githubusercontent.com/23561673/233441856-cdbd3612-e43c-44c0-a633-8aa2cad0b9fc.png">

Not sure if this is due to how the Chef scripts are installing the software and the add-on can't detect or something else. Any thoughts?

Thanks!

**Comment by cameronkroeker** [comment]
Hi @tatornator12,

There should be an `ESRI.properties.<hostname or ip>.<version>` file inside the arcgis run_as user account home directory. This file contains the information about which products are installed (product names, version, and install directory path). For example:

```
/home/arcgis/.ESRI.properties.ip-10-0-0-39.11.0
```

Perhaps either this file isn't present, or maybe the `Excalibur-Setup.sh` is not able to locate it.

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
@tatornator12 

I dug into the `Excalibur-Setup.sh` script and notice it will use this to find the .Esri.properties file to check which products are installed:

`${UserHome}/.ESRI.properties.$(uname -n).${TempArcGISVersion}`

I suspect the `uname -n` could be problematic in AWS EC2 instances. For example, if the .Esri.properties file name contains the ip rather than what is returned by `uname -n` then it may not be able to locate the file.

On the EC2 instance run the command `uname -n` and compare it with the actual .Esri.properties file name to see if it matches.

**Comment by tatornator12** [comment]
Thanks for the quick response back @cameronkroeker. I was hoping that would be the issue but looks like everything looks good:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/23561673/233645364-b6ec43c2-fdab-496d-8b1a-2ef9aae67f18.png">

**Comment by tatornator12** [comment]
@cameronkroeker

I believe I found the issue which isn't documented well for the Excalibur installation: https://doc.arcgis.com/en/excalibur/latest/get-started/install-and-authorize-arcgis-excalibur.htm.

The first step says to login as a user with admin privs, which I do by `sudo su` to root. However, what I just tried was to change to the arcgis user and try running the shell script again. Doing so, let me install Excalibur finally. So it appears that the add-on wants you to be logged in as the user who installed the ArcGIS software, at least on Linux.

Thanks for the assist!
