### ISSUE TITLE
Purpose of "recipe[arcgis-enterprise::disable_loopback_check]"

### ISSUE THREAD

**Issue by Ayushyadav19** [Esri/arcgis-cookbook#356]
Hi @cameronkroeker ,

Can you please tell me the use/purpose of the "recipe[arcgis-enterprise::disable_loopback_check]"?

![image](https://github.com/Esri/arcgis-cookbook/assets/70343349/6be2210a-05d1-4af8-958b-e8557a83060f)

Any help will be highly appreciated!

Thanks
Ayush

**Comment by cameronkroeker** [comment]
Hi @Ayushyadav19,

The disable_loopback_check recipe is really only needed if you will be referencing a shared location for your portal content and/or server config-store directories by an alias rather than the actual file server hostname (`\\FileServerAlias\share`). It implements method 1 from the following Microsoft KB:

https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/accessing-server-locally-with-fqdn-cname-alias-denied#resolution

https://github.com/Esri/arcgis-cookbook/blob/b6eba15c34cd5bbb192df830f395b3d5aea0e735/cookbooks/arcgis-enterprise/recipes/disable_loopback_check.rb#L20-L42

Thanks,
Cameron K.

**Comment by Ayushyadav19** [comment]
Thanks! @cameronkroeker. Really appreciated!

**Comment by cameronkroeker** [comment]
> Thanks! @cameronkroeker. Really appreciated!

You're welcome!
