### ISSUE TITLE
Fully Qualified Domain Name

### ISSUE THREAD

**Issue by micahwilli** [Esri/arcgis-cookbook#50]
In Configuring Web Adaptor with Portal the Fully Qualified Domain Name is needed. I am running this in an EDN environment on Amazon Web Services. The FQDN and the CPU name are the same name with the addition of ".local". When the cookbook gets all the way to recipe[arcgis::portal_wa] and breaks because it thinks there is no FQDN. Is there any way this can be added as a variable? As in IF  domain = "workspace" add .local to the CPU name?

**Comment by pbobov** [comment]
You can change the URLs used by 'Configure Web Adaptor with Portal' by setting  *['arcgis']['portal']['url']* and *['arcgis']['portal']['local_url']* attributes in the JSON file.

See portal_wa.rb recipe:
```
...
arcgis_webadaptor 'Configure Web Adaptor with Portal' do
  portal_url node['arcgis']['portal']['url']
  portal_local_url node['arcgis']['portal']['local_url']
  install_dir node['arcgis']['web_adaptor']['install_dir']
  instance_name node['arcgis']['portal']['wa_name']
  username node['arcgis']['portal']['admin_username']
  password node['arcgis']['portal']['admin_password']
  action :configure_with_portal
end
...
```

The default values for these attributes are:
```
default['arcgis']['portal']['url'] = 'https://' + node['arcgis']['portal']['domain_name'] + '/' + node['arcgis']['portal']['wa_name']
default['arcgis']['portal']['local_url'] = 'https://' + node['fqdn'] + ':7443/arcgis'
```

**Comment by dgrmit** [comment]
Although **micahwilli** posted his problem and question regarding an FQDN check a little while back, I thought I'd share my workaround to the this problem in case others are looking for a quick solution.

While trying to do a full WebGIS stack install (Server, Data Store, Portal and Federation), I struggled with the FQDN requirement for the Portal Web Adaptor configuration. When I tried to change the Portal _url_ and _local_url_ (which is now _private_url_) as suggested by **pbobov**, other parts of the script failed (namely the Portal configuration stage, which failed with a "Not found" error, and the Federation stage which was totally broken [that is, I couldn't even manually get it working!]). This may have been due to my understanding of the different URLs and my config of them in the JSON file, or how the FQDN (or lack of) was used differently in the various sections of the code.

Either way, to fix my issue of building a dev server without a domain (or FQDN) I first needed to include "domain_name" as _<servername>.local_ in the JSON file for both the _['arcgis']['server']_ and _['arcgis']['portal']_ nodes. Eg:
    
**webgis-windows.json**

    ...
    "server":{
       ...
       "domain_name": "webgis.local",
       ...
    }
    "portal":{
       ...
        "domain_name": "webgis.local",
       ...
    }

I did not include any extra URL attributes in the JSON file (the default values which were generated by the scripts worked fine).

I then needed to edit Webadaptor.rb (found in _\cookbooks\arcgis-server\providers_) to correctly update the Portal Web Context and Portal URLs to correctly configure the Portal Web Adaptor.

So, I replaced these lines (lines 164 - 66) in **Webadaptor.rb** 

    ...
    wa_url = @new_resource.portal_wa_url + '/webadaptor'
    uri = URI.parse(@new_resource.portal_url)
    portal_url = uri.scheme + '://' + uri.host + ':' + uri.port.to_s
    ...

with this code:
 
    ...
    wuri = URI.parse(@new_resource.portal_wa_url)
    uri = URI.parse(@new_resource.portal_url)
	
    if not wuri.host.include? "."
	    wa_url = wuri.scheme + '://' + wuri.host + '.local' + wuri.path + '/webadaptor'
    else
            wa_url = @new_resource.portal_wa_url + '/webadaptor'
    end

    if not uri.host.include? "."
           uri.host = uri.host + '.local'
    end
	
    portal_url = uri.scheme + '://' + uri.host + ':' + uri.port.to_s
    ...

This code block simply checks if the host name of the _portal_wa_url_ and _portal_url_ variables includes a ".", which would indicate an FQDN. If it does not, it appends a _.local_ to the host name so that the a valid FQDN is passed to the web adaptor configurator.

Once I made this change, the full stack installation worked correctly in my FQDN-less dev environment (and I can even use the non-FQDN URLs to get to the Portal and ArcGIS Server web pages).

It probably isn't the best solution (I'm still quite new to Portal/Server and the Ruby language), but hopefully it helps someone else struggling with this problem.
