### ISSUE TITLE
Uninstalling Pro Bug

### ISSUE THREAD

**Issue by steveoh** [Esri/arcgis-cookbook#90]
I noticed that the pro utilites file is looking for the product code in [local machine](https://github.com/Esri/arcgis-cookbook/blob/master/cookbooks/arcgis-pro/libraries/utils.rb#L27) but mine was placed in `current_user`. Therefore I cannot uninstall pro with chef.

```
Recipe: arcgis-pro::uninstall
  * arcgis_pro_pro[Uninstall ArcGIS Pro] action uninstall[2017-06-08T13:37:41-06:00] INFO: Processing arcgis_pro_pro[Uninstall ArcGIS Pro] action uninstall (arcgis-pro::uninstall line 20)
 (skipped due to only_if)
```

![image](https://user-images.githubusercontent.com/325813/26947639-ac28f280-4c50-11e7-814e-35bf0e6cc613.png)

**Comment by pbobov** [comment]
In my tests the product codes end up in LOCAL_MACHINE hive in registry.

Did you install Pro manually or using Chef? Did you install service packs or language packs?

So far Chef coookbook for Pro does not support installing and uninstalling language packs and service packs.  You will need to specify product code using node['arcgis']['pro']['product_code'] attribute to make arcgis cookbook work with LPs and SPs.

**Comment by steveoh** [comment]
I installed using chef. I may or may not have installed the service pack but I did not install any language packs.

**Comment by cameronkroeker** [comment]
This is likely because of the following attribute:

`node['arcgis']['pro']['allusers'] = Defines installation context of ArcGIS Pro, 1 - per machine and 2 - per user. Default value is '2'.`

If all_users is not defined in json file then it defaults to 2 (current user). Otherwise if all_users = 1 is defined in json file then its per machine and registry is placed in LOCAL_MACHINE.
