### ISSUE TITLE
Support authorization using provisioning file

### ISSUE THREAD

**Issue by dmcd** [Esri/arcgis-cookbook#94]
Hi there,

I would like to supply a provisioning file (.prvc) for authorizing ArcGIS Server, however the cookbooks don't provide an option for supplying the email address which is [required](http://server.arcgis.com/en/server/latest/install/linux/silently-install-arcgis-server.htm#ESRI_SECTION1_49ED6300B7144B35BFF3AB749743EB5F) when using a provisioning file.

**Comment by pbobov** [comment]
The ArcGIS Chef cookbooks do not support supplying e-mail address during software authorization with .prvc files because we assumed that .prvc files provided by end users would always contain e-mail addresses in them, and that .prvc files without e-mail addresses are used only internally during the software development cycle.

**Comment by dmcd** [comment]
Oh ok. I presumed I needed to supply the email address as an argument, but works ok without it.

Thanks
